name: dapqa mongo tests

on:
  workflow_dispatch:

jobs:
  parallel:
    uses: ./.github/workflows/dockertests.yml
    with:
      command-json-array: >
        [
        "make mongo_test",
        "make MONGO_VERSION=\"7.0.2\" MONGO_MAJOR=\"7.0\" MONGO_REPO=\"repo.mongodb.org\" MONGO_PACKAGE=\"mongodb-org\" mongo_features",
        "make MONGO_VERSION=\"7.0.2\" MONGO_MAJOR=\"7.0\" MONGO_REPO=\"repo.mongodb.org\" MONGO_PACKAGE=\"mongodb-enterprise\" mongo_features",
        "make MONGO_VERSION=\"6.0.3\" MONGO_MAJOR=\"6.0\" MONGO_REPO=\"repo.mongodb.org\" MONGO_PACKAGE=\"mongodb-org\" mongo_features",
        "make MONGO_VERSION=\"6.0.3\" MONGO_MAJOR=\"6.0\" MONGO_REPO=\"repo.mongodb.com\" MONGO_PACKAGE=\"mongodb-enterprise\" mongo_features",
        "make MONGO_VERSION=\"5.0.13\" MONGO_MAJOR=\"5.0\" MONGO_REPO=\"repo.mongodb.org\" MONGO_PACKAGE=\"mongodb-org\" mongo_features",
        "make MONGO_VERSION=\"5.0.13\" MONGO_MAJOR=\"5.0\" MONGO_REPO=\"repo.mongodb.com\" MONGO_PACKAGE=\"mongodb-enterprise\" mongo_features",
        "make MONGO_VERSION=\"4.4.17\" MONGO_MAJOR=\"4.4\" MONGO_REPO=\"repo.mongodb.org\" MONGO_PACKAGE=\"mongodb-org\" mongo_features",
        "make MONGO_VERSION=\"4.4.17\" MONGO_MAJOR=\"4.4\" MONGO_REPO=\"repo.mongodb.com\" MONGO_PACKAGE=\"mongodb-enterprise\" mongo_features",
        "make redis_test",
        "make REDIS_VERSION=\"5.0.8\" redis_features",
        "make REDIS_VERSION=\"6.0.8\" redis_features",
        "make REDIS_VERSION=\"6.2.4\" redis_features",
        "make FEATURE=\"backup\" REDIS_VERSION=\"5.0.8\" redis_features",
        "make FEATURE=\"backup\" REDIS_VERSION=\"6.0.8\" redis_features",
        "make FEATURE=\"backup\" REDIS_VERSION=\"6.2.4\" redis_features",
        ]
